# Auto-generated by `python manage.py makemigrations` after adding the
# `logo` and `accent_color` fields to BusinessAccount (see
# accounts/models.py). This is a plain SCHEMA migration — just adds two
# new columns to the existing table, no data to backfill, so Django wrote
# the whole thing itself with no need to hand-edit it (contrast with
# invoicing/migrations/0002_seed_default_tender_types.py, which is a DATA
# migration we wrote by hand).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='accent_color',
            field=models.CharField(default='#059669', max_length=7),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
