# Generated by Django 6.1.1 on 2026-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_businessaccount_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='calendar_accent',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('ocean', 'Ocean'), ('sunset', 'Sunset'), ('grape', 'Grape'), ('rose', 'Rose'), ('slate', 'Slate')], default='emerald', max_length=20),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='theme_accent',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('ocean', 'Ocean'), ('sunset', 'Sunset'), ('grape', 'Grape'), ('rose', 'Rose'), ('slate', 'Slate')], default='emerald', max_length=20),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='theme_background',
            field=models.CharField(choices=[('default', 'Default'), ('ocean', 'Ocean Theme'), ('jungle', 'Jungle Theme'), ('sunset', 'Sunset Theme')], default='default', max_length=20),
        ),
    ]
