# Generated by Django 6.1.1 on 2026-09-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_businessaccount_calendar_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='theme_nav',
            field=models.CharField(choices=[('default', 'Default'), ('emerald', 'Emerald'), ('ocean', 'Ocean'), ('sunset', 'Sunset'), ('grape', 'Grape'), ('rose', 'Rose'), ('slate', 'Slate')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='theme_background',
            field=models.CharField(choices=[('default', 'Default'), ('emerald-tint', 'Emerald Tint'), ('ocean-tint', 'Ocean Tint'), ('sunset-tint', 'Sunset Tint'), ('grape-tint', 'Grape Tint'), ('rose-tint', 'Rose Tint'), ('slate-tint', 'Slate Tint'), ('ocean', 'Ocean Theme'), ('jungle', 'Jungle Theme'), ('sunset', 'Sunset Theme'), ('tropical', 'Tropical'), ('horizon', 'Sunset Horizon'), ('waves', 'Ocean Waves'), ('summit', 'Mountain Summit')], default='default', max_length=20),
        ),
    ]
