# Generated by Django 6.1.1 on 2026-09-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_businessaccount_theme_nav_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='theme_nav',
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='calendar_accent',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('teal', 'Teal'), ('ocean', 'Ocean'), ('lagoon', 'Lagoon'), ('indigo', 'Indigo'), ('grape', 'Grape'), ('twilight', 'Twilight'), ('berry', 'Berry'), ('rose', 'Rose'), ('crimson', 'Crimson'), ('sunset', 'Sunset'), ('amber', 'Amber'), ('slate', 'Slate'), ('midnight', 'Midnight')], default='emerald', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='theme_accent',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('teal', 'Teal'), ('ocean', 'Ocean'), ('lagoon', 'Lagoon'), ('indigo', 'Indigo'), ('grape', 'Grape'), ('twilight', 'Twilight'), ('berry', 'Berry'), ('rose', 'Rose'), ('crimson', 'Crimson'), ('sunset', 'Sunset'), ('amber', 'Amber'), ('slate', 'Slate'), ('midnight', 'Midnight')], default='emerald', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='theme_background',
            field=models.CharField(choices=[('default', 'Default'), ('emerald-tint', 'Emerald Tint'), ('teal-tint', 'Teal Tint'), ('ocean-tint', 'Ocean Tint'), ('lagoon-tint', 'Lagoon Tint'), ('indigo-tint', 'Indigo Tint'), ('grape-tint', 'Grape Tint'), ('twilight-tint', 'Twilight Tint'), ('berry-tint', 'Berry Tint'), ('rose-tint', 'Rose Tint'), ('crimson-tint', 'Crimson Tint'), ('sunset-tint', 'Sunset Tint'), ('amber-tint', 'Amber Tint'), ('slate-tint', 'Slate Tint'), ('midnight-tint', 'Midnight Tint'), ('ocean', 'Ocean Theme'), ('jungle', 'Jungle Theme'), ('sunset', 'Sunset Theme'), ('berry', 'Berry Theme'), ('amber', 'Amber Theme'), ('tropical', 'Tropical'), ('horizon', 'Sunset Horizon'), ('waves', 'Ocean Waves'), ('summit', 'Mountain Summit')], default='default', max_length=20),
        ),
    ]
