# Generated by Django 6.1.1 on 2026-10-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_businessaccount_theme_nav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
