# Generated by Django 6.1.1 on 2026-10-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpagephoto',
            options={'ordering': ['display_order', 'id']},
        ),
    ]
