# Generated by Django 6.1.1 on 2026-09-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='low_stock_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='low_stock_snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
