# Generated by Django 6.1.1 on 2026-09-20 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_seed_default_tender_types'),
        ('scheduling', '0002_appointment_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='scheduling.appointment'),
        ),
    ]
