# Generated by Django 6.1.1 on 2026-09-21 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('quote', 'Quote'), ('void', 'Void')], default='unpaid', max_length=10),
        ),
    ]
