# Generated by Django 6.1.1 on 2026-09-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoicelineitem_discount_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
