# Generated by Django 6.1.1 on 2026-09-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_remove_invoicelineitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='void_note',
            field=models.TextField(blank=True),
        ),
    ]
