# Generated by Django 6.1.1 on 2026-09-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoicelineitem_is_voided_invoicelineitem_void_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
