# Auto-generated by `python manage.py makemigrations campaigns` — plain
# schema migration creating the Campaign and Lead tables from scratch
# (see campaigns/models.py). Nothing hand-written here.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('details', models.TextField(blank=True)),
                ('share_link_slug', models.SlugField(unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('qr_scan_count', models.PositiveIntegerField(default=0)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='campaign_qr_codes/')),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interested_in', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted')], default='new', max_length=10)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
